namespace StartupConnect.Models;

public class IdeaAnalysis
{
    public int Id { get; set; }
    
    public int IdeaId { get; set; }
    public Idea Idea { get; set; } = null!;

    public string Summary { get; set; } = string.Empty;
    public string ProblemsAndSolutions { get; set; } = string.Empty;
    public string TargetUsers { get; set; } = string.Empty;
    public string MarketPotential { get; set; } = string.Empty;
    public string Risks { get; set; } = string.Empty;
    public string RevenueModels { get; set; } = string.Empty;
    public string TeamSuggestions { get; set; } = string.Empty;
    
    public int OverallScore { get; set; }
    
    // JSON string containing list of similar ideas
    public string SimilarIdeasJson { get; set; } = "[]";

    /// <summary>
    /// A brief 2-sentence investor-facing pitch generated by Gemini (gemini-3.6-flash).
    /// Derived from the already-stored Summary + MarketPotential fields — not the raw idea text.
    /// Null until first generation; cached permanently thereafter.
    /// </summary>
    public string? InvestorPitchSummary { get; set; }

    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
}
